# Generated by Django 5.0.6 on 2024-06-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Напишите имя сотрудника"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="@gmail.com",
                        max_length=254,
                        verbose_name="Укажите вашу почту",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="programming_blog/", verbose_name="Загрузите фото"
                    ),
                ),
                ("about_emp", models.TextField(verbose_name="Опишите сотрудника")),
                (
                    "date_of_birth",
                    models.DateField(verbose_name="Укажите дату рождения"),
                ),
                (
                    "programmer_choices",
                    models.CharField(
                        choices=[
                            ("FULLSTACK", "FULLSTACK"),
                            ("BACKEND DEVELOPER", "BACKEND DEVELOPER"),
                            ("FRONT DEVELOPER", "FRONT DEVELOPER"),
                            ("UX-UI", "UX-UI"),
                            ("SYSTEM DEVELOPER", "SYSTEM DEVELOPER"),
                        ],
                        max_length=100,
                        verbose_name="Выберите категорию программиста",
                    ),
                ),
                (
                    "rezume",
                    models.FileField(
                        upload_to="rezume/", verbose_name="Загрузите резюме"
                    ),
                ),
                (
                    "github",
                    models.URLField(verbose_name="Вставьте ссылку на ваш GITHUB"),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
